/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bike_shop_application;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Kian Barker & Gaving Judge 28/11/22
 */
public class purchase_item extends javax.swing.JFrame {

    /**
     * Creates new form purchase_item
     */
    public purchase_item() {
        initComponents();
        what_item_to_purchase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Push Bike", "Electric Bike", "Petrol Bike", "Helmets", "Lights", "Chains" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        what_item_to_purchase = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        how_many_purchase = new javax.swing.JTextField();
        save_purchase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase an item");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Purchase an item ");

        jLabel2.setText("What item do you wish to purchase:");

        what_item_to_purchase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("How many items do you want:");

        save_purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike_shop_application/save.png"))); // NOI18N
        save_purchase.setText("Save");
        save_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_purchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(what_item_to_purchase, 0, 186, Short.MAX_VALUE)
                    .addComponent(how_many_purchase)
                    .addComponent(save_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(what_item_to_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(how_many_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(save_purchase)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_purchaseActionPerformed
        // TODO add your handling code here:
        ArrayList readValues = new ArrayList();
        ArrayList salesReference = new ArrayList();
        LocalDate date = java.time.LocalDate.now();
        AllConnections connect = new AllConnections();
        connect.selectAllCurrentStock(readValues);
        String tempValue = what_item_to_purchase.getSelectedItem().toString();
        String subtract = how_many_purchase.getText();
        int newSubtract = Integer.parseInt(subtract);
        
        
        String value = "";
        int number = 0;
     
        if (tempValue == "Push Bike")
        {
            int x = (int) readValues.get(0);
            value = "push_bikes";
            number = x - newSubtract;
                    
        } else if (tempValue == "Electric Bike")
        {
            int x = (int) readValues.get(1);
            value = "electric_bike";
            number = x - newSubtract;
        }  else if (tempValue == "Petrol Bike")
        {
            int x = (int) readValues.get(2);
            value = "petrol_bike";
            number = x - newSubtract;
        }  else if (tempValue == "Helmets")
        {
            int x = (int) readValues.get(3);
            value = "helmets";
            number = x - newSubtract;
        }  else if (tempValue == "Lights")
        {
            int x = (int) readValues.get(4);
            value = "lights";
            number = x - newSubtract;
        } else 
        {
            int x = (int) readValues.get(5);
            value = "chains";
            number = x - newSubtract;
        }
        
        connect.updateCurrentStock(value, number);
        connect.motifySales(what_item_to_purchase.getSelectedItem().toString(), newSubtract, date);
        connect.motifySalesReferenceList(salesReference);
  
        String welcomeMessage = "You have purchase a " + what_item_to_purchase.getSelectedItem() + " Your reference number is " + salesReference.get(salesReference.size() - 1);
        JOptionPane.showMessageDialog(null, welcomeMessage);
        this.dispose();   
    }//GEN-LAST:event_save_purchaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase_item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField how_many_purchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton save_purchase;
    private javax.swing.JComboBox<String> what_item_to_purchase;
    // End of variables declaration//GEN-END:variables

    private boolean readValues(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
